title: Instituto Privado de Enseñanza Musical
short_title: IPEM
description: IPEM se dedica desde el año 1986 a la enseñanza musical. Buscamos ayudarte a realizar tus primeros pasos en la música o enriquecer lo que ya sabes.
baseurl:
url: "https://adebrouvier.github.io/ipem-cms"
permalink: "/:path/"
defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
collections:
  people:
    output: true
    permalink: "/about/:path/"
  posts:
    output: true
    permalink: "/blog/:path/"
  courses:
    output: true
    permalink: "/talleres/:path/"
# tag_page_layout: tag_page
# tag_page_dir: tag
jekyll-archives:
  enabled: all
  layout: "archive"

# jekyll-seo-tag
social:
  name: Instituto Privado de Enseñanza Musical
  links:
    - https://www.twitter.com/ipemcr
    - https://www.facebook.com/ipem.cr
    - https://www.instagram.com/ipemcomodororivadavia
    - https://www.youtube.com/channel/UCeSQ99ApVWQfJlayppctdEQ

twitter:
  username: ipemcr
  card: summary

lang: es_AR

logo: /img/logo.png

google_analytics_id: UA-103656812-1

plugins:
  - jekyll-menus
  - jekyll-feed
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
