name: Combine PRs

on:
  workflow_dispatch:

jobs:
  combine-prs:
    runs-on: ubuntu-latest

    steps:
      - name: combine-prs
        id: combine-prs
        uses: github/combine-prs@v5.1.0
        with:
          select_label: combine
